### ISSUE TITLE
Enhanced search APIs for CDEs

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-cde-server#9]
We will implement a REST-based search API in the CDE microservice (#6) that will allow the user to find those CDEs that have certain values in specified attributes. Initial search criteria will include the CDE identifier and  name. Time permitting, we may implement support for additional search criteria (see Task 16). We will evaluate support for wild cards or regular expressions in the search strings.

Task 9 in https://docs.google.com/document/d/1Mc0MHJN27AN27eBskPiGnoNZ91yd49EW4UYu3aJSjW4/edit#

Enhanced CDE search front end task:
https://github.com/metadatacenter/cedar-template-server/issues/55

Depends on metadatacenter/cedar-resource-server#55

**Comment by martinjoconnor** [comment]
Front end task here: https://github.com/metadatacenter/cedar-template-server/issues/55

**Comment by martinjoconnor** [comment]
Initially, provide search for public ID, version, publication status, name, description.
Wildcard and regex search on those field? Also exact match, partial match.

**Comment by martinjoconnor** [comment]
Example from Nexus:

![screen shot 2018-09-05 at 3 49 33 pm](https://user-images.githubusercontent.com/1731323/45125455-6a49e700-b123-11e8-9fd9-139c0136a9be.png)

**Comment by graybeal** [comment]
Include 1-digit or 2-digit numbers?

**Comment by martinjoconnor** [comment]
Yup -updated above.
